MODULE_TOPDIR = ../..

PROGRAMS=r.spread.sod test.rspreadsod.date

LIBES = $(RASTERLIB) $(GISLIB) $(MATHLIB) $(VECTORLIB)
DEPENDENCIES = $(RASTERDEP) $(GISDEP) $(VECTORDEP)
EXTRA_LIBS = $(GDALLIBS) $(OMPLIB)
EXTRA_CFLAGS = $(GDALCFLAGS) -D SOD_TEST -O0 -std=c++11 -Wall -Wextra -fpermissive $(OMPCFLAGS) $(VECT_CFLAGS)
EXTRA_INC = $(VECT_INC)

r_spread_sod_OBJS = main.o Spore.o Img.o
test_rspreadsod_date_OBJS = test_date_main.o

include $(MODULE_TOPDIR)/include/Make/Multi.make

LINK = $(CXX)

ifneq ($(strip $(CXX)),)
default: multi
endif
