name: CI with UbuntuGIS PPA

on:
  push:
  pull_request:
  schedule:
  # 01:00 Pacific Time (in UTC), every Friday (morning)
  - cron:  '0 8 * * 5'

jobs:
  test-with-ubuntugis-ppa:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Add PPA
      run: |
        sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
    - name: Install GRASS GIS and other dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y -qq grass grass-dev grass-doc
    - name: Install the module
      run: |
        grass --tmp-location XY --exec g.extension extension=r.pops.spread url=. --verbose
    - name: Cache data for testing
      id: cache-nc_spm_08_grass7
      uses: actions/cache@v1
      with:
        path: nc_spm_08_grass7
        key: ${{ runner.os }}-nc_spm_08_grass7
    - name: Get sample data for testing (NC SPM sample location)
      if: steps.cache-nc_spm_08_grass7.outputs.cache-hit != 'true'
      run: |
        grass --tmp-location XY --exec g.extension g.download.location --verbose
        grass --tmp-location XY --exec g.download.location url=https://grass.osgeo.org/sampledata/north_carolina/nc_spm_08_grass7.tar.gz dbase=~ --verbose
    - name: Run test (manually specified files)
      run: |
        cd testsuite/
        grass -c ~/nc_spm_08_grass7/test --exec ./test_r_pops_spread.py
        rm -rf ~/nc_spm_08_grass7/test
